global:
  scrape_interval: 15s

scrape_configs:
  # Model API (déjà chez toi normalement)
#  - job_name: 'model-api'
#    static_configs:
#      - targets: ['model-api:8000']

  # Scrape du script train.py (exporteur direct sur port 8000)
  - job_name: "ml_training"
    static_configs:
      - targets: ["train:8000"]   
      
  # Pushgateway pour jobs batch (entrainement)
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']



  # Scrape du script train.py (exporteur direct sur port 8000)
  - job_name: "ml_training"
    static_configs:
      - targets: ["train:8000"]   # adapte si ton conteneur train.py est appelé autrement



